// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5n2mHZcxO9ROTZbrobaroYnqNLKL2s1o',
    appId: '1:646928335818:web:57714d3b6972c04b698533',
    messagingSenderId: '646928335818',
    projectId: 'event-map-app-aab7b',
    authDomain: 'event-map-app-aab7b.firebaseapp.com',
    databaseURL: 'https://event-map-app-aab7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'event-map-app-aab7b.firebasestorage.app',
    measurementId: 'G-3YYZN56TTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtjnAebpnMWEnylAbTxJLQz59qSoIHso',
    appId: '1:646928335818:android:7e3d115a399f3570698533',
    messagingSenderId: '646928335818',
    projectId: 'event-map-app-aab7b',
    databaseURL: 'https://event-map-app-aab7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'event-map-app-aab7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBksbp_Xw96C3VZqtK1fNlgmuUxzHQVskQ',
    appId: '1:646928335818:ios:0fff741e6c065d5e698533',
    messagingSenderId: '646928335818',
    projectId: 'event-map-app-aab7b',
    databaseURL: 'https://event-map-app-aab7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'event-map-app-aab7b.firebasestorage.app',
    iosBundleId: 'com.example.eventMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBksbp_Xw96C3VZqtK1fNlgmuUxzHQVskQ',
    appId: '1:646928335818:ios:0fff741e6c065d5e698533',
    messagingSenderId: '646928335818',
    projectId: 'event-map-app-aab7b',
    databaseURL: 'https://event-map-app-aab7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'event-map-app-aab7b.firebasestorage.app',
    iosBundleId: 'com.example.eventMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5n2mHZcxO9ROTZbrobaroYnqNLKL2s1o',
    appId: '1:646928335818:web:0e76a9a8d9df07c6698533',
    messagingSenderId: '646928335818',
    projectId: 'event-map-app-aab7b',
    authDomain: 'event-map-app-aab7b.firebaseapp.com',
    databaseURL: 'https://event-map-app-aab7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'event-map-app-aab7b.firebasestorage.app',
    measurementId: 'G-X632HDMMPE',
  );
}
